# Theme settings
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

# Site settings
title: Venue Filler
description: Documentation for Venue Filler
show_downloads: false

# Markdown settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Navigation structure
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: default

# Navigation (you'll need to implement this in your layout)
navigation:
  - title: "Home"
    url: /
  - title: "Development Guide"
    url: /development-guide/
    children:
      - title: "Security Scanning"
        url: /development-guide/security-scanning.md
  - title: "Installation"
    url: /installation/
  - title: "User Guide"
    url: /user-guide/
    children:
      - title: "Glossary"
        url: /user-guide/glossary.md