remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Venue Filler
description: Documentation for Venue Filler
show_downloads: false

# Navigation
nav:
  - name: "Home"
    link: "/"
  - name: "Development Guide"
    link: "/development-guide/"
    subnav:
      - name: "Security Scanning"
        link: "/development-guide/security-scanning.md"
  - name: "Installation"
    link: "/installation/"
  - name: "User Guide"
    link: "/user-guide/"

# Optional: You can add custom CSS for further dark mode adjustments
# custom_css: custom.css